[versions]
[versions.androidx]
androidxActivity = "1.6.1"
androidxAnnotation = "1.5.0"
androidxAppCompat = "1.5.1"
androidxAutofill = "1.1.0"
androidxCore = "1.9.0"
androidxCoreSplashscreen = "1.0.0"
androidxConstraintLayout = "2.1.4"
androidxViewPager = "1.0.0"

[versions.androidx.fragment]
androidxFragment = "1.5.4"

[versions.androidx.lifecycle]
androidxLifecycle = "2.6.0-alpha05"

[versions.androidx.camerax]
cameraxCore = "1.2.0-rc01"

[versions.androidx.datastore]
androidxDataStore = "1.0.0"

[versions.androidx.navigation]
androidxNavigation = "2.5.3"

[versions.google]
barcodeMlKit = "18.1.0"
zxing = "3.5.1"

[versions.google.firebase]
firebaseBom = "31.2.0"
firebaseCrashlyticsPlugin = "2.9.2"
firebasePerfPlugin = "1.4.2"

[versions.google.playservices]
gmsAuth = "20.3.0"
gmsPlugin = "4.3.14"
gmsPhone = "18.0.1"
gmsLocation = "21.0.1"

[versions.gradle]
gradlePlugin = "7.4.1"

[versions.utils]
glide = "4.14.2"
timber = "5.0.1"
shimmer = "0.5.0"
libPhoneNumber = "8.12.57"

[versions.junit]
junit4 = "4.13.2"
junitTestExt = "1.1.3"

[versions.test]
mockk = "1.13.2"
turbine = "0.12.1"

[versions.dagger]
hilt = "2.44.2"
hiltExt = "1.0.0"

[versions.kotlin]
kotlin = "1.8.0"
kotlinxCoroutines = "1.6.4"
kotlinxSerializationJson = "1.4.1"

[versions.networking]
okhttp = "4.10.0"
retrofit = "2.9.0"
retrofitKotlinxSerializationJson = "0.8.0"

# Probably won't be used
[versions.other]
desugarJdkLibs = "1.2.2"
androidxBrowser = "1.4.0"
androidxEspresso = "3.5.0"
androidxMacroBenchmark = "1.1.1"
androidxMetrics = "1.0.0-alpha03"
androidxProfileinstaller = "1.2.1"
androidxStartup = "1.1.1"
androidxTestCore = "1.5.0"
androidxTestExt = "1.1.4"
androidxTestRules = "1.5.0"
androidxTestRunner = "1.5.1"
androidxTracing = "1.1.0"
androidxUiAutomator = "2.2.0"
androidxWindowManager = "1.0.0"
androidxWork = "2.7.1"
lint = "30.3.1"
room = "2.5.0"
secrets = "2.0.1"


[libraries]
[libraries.androidx]


[libraries.androidx.fragment]

[libraries.androidx.lifecycle]

[libraries.androidx.camerax]

[libraries.androidx.datastore]

[libraries.androidx.navigation]

[libraries.google]

[libraries.google.firebase]

[libraries.google.playservices]

[libraries.gradle]

[libraries.utils]

[libraries.junit]

[libraries.test]

[libraries.dagger]

[libraries.kotlin]

[libraries.networking]

[libraries.other]


[plugins]