# Workflow for PR checks
name: Android CI
# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events on develop branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  # For testing purposes
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository
      - uses: actions/checkout@v3
      
#       (currently disabled)
#       # Prepares google-services.json file
#       - name: Prepare google services file
#         uses: timheuer/base64-to-file@v1.1
#         with:
#           fileName: google-services.json
#           fileDir: ./app/
#           encodedString: ${{ secrets.GOOGLE_SERVICES_BASE64 }}

      # Sets up the JDK version
      - name: Set up JDK environment
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11.0.12
          distribution: temurin

      # Sets up Gradle Caching
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/main' }}

      # Checks whether the app builds
      - name: Build APK
        run: ./gradlew assembleDebug --scan
        
      # Runs ktlint checks
      - name: Run ktlint
        run: ./gradlew ktlint
